name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: SimulacaoContinuousDelivery
        uses: actions/upload-artifact@v7
        with:
          name: projetozip.zip
          path: |
            '**.py'
            README.md
